//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Borrow
    {
        public int Id_imprumut { get; set; }
        public string Id_user { get; set; }
        public Nullable<int> Id_carte { get; set; }
        public string Date { get; set; }

        [Required]
        [Range(1, 5, ErrorMessage = "Introdu un numar valid")]
        public string Nr_carti { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Carti Carti { get; set; }
    }
}
