//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginBiblioteca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carti()
        {
            this.Borrows = new HashSet<Borrow>();
        }
    
        public int Id { get; set; }
        public string Nume_carte { get; set; }
        public string Autor { get; set; }
        public string Editura { get; set; }
        public Nullable<int> Nr_Total { get; set; }
        public Nullable<int> Nr_Disponibil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Borrow> Borrows { get; set; }
    }
}
